# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class Array(object):
    NONE = 0
    ArrayInt8 = 1
    ArrayInt16 = 2
    ArrayInt32 = 3
    ArrayInt64 = 4
    ArrayFloat = 5
    ArrayDouble = 6
