# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

from typing import Optional

import flatbuffers
from flatbuffers.compat import import_numpy
from flatbuffers.table import Table

np = import_numpy()


class DimensionMetaData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DimensionMetaData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDimensionMetaData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def DimensionMetaDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x68\x73\x30\x32", size_prefixed=size_prefixed
        )

    # DimensionMetaData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DimensionMetaData
    def Label(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DimensionMetaData
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DimensionMetaData
    def Unit(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DimensionMetaData
    def BinBoundariesType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DimensionMetaData
    def BinBoundaries(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None


def DimensionMetaDataStart(builder: flatbuffers.Builder):
    builder.StartObject(5)


def Start(builder: flatbuffers.Builder):
    DimensionMetaDataStart(builder)


def DimensionMetaDataAddLabel(builder: flatbuffers.Builder, label: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0
    )


def AddLabel(builder: flatbuffers.Builder, label: int):
    DimensionMetaDataAddLabel(builder, label)


def DimensionMetaDataAddLength(builder: flatbuffers.Builder, length: int):
    builder.PrependInt32Slot(1, length, 0)


def AddLength(builder: flatbuffers.Builder, length: int):
    DimensionMetaDataAddLength(builder, length)


def DimensionMetaDataAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0
    )


def AddUnit(builder: flatbuffers.Builder, unit: int):
    DimensionMetaDataAddUnit(builder, unit)


def DimensionMetaDataAddBinBoundariesType(
    builder: flatbuffers.Builder, binBoundariesType: int
):
    builder.PrependUint8Slot(3, binBoundariesType, 0)


def AddBinBoundariesType(builder: flatbuffers.Builder, binBoundariesType: int):
    DimensionMetaDataAddBinBoundariesType(builder, binBoundariesType)


def DimensionMetaDataAddBinBoundaries(builder: flatbuffers.Builder, binBoundaries: int):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(binBoundaries), 0
    )


def AddBinBoundaries(builder: flatbuffers.Builder, binBoundaries: int):
    DimensionMetaDataAddBinBoundaries(builder, binBoundaries)


def DimensionMetaDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return DimensionMetaDataEnd(builder)
