# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()


class ArrayElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsArrayElement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArrayElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def ArrayElementBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset,
                                                    b"\x6E\x73\x31\x31",
                                                    size_prefixed=size_prefixed)

    # ArrayElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArrayElement
    def VType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags,
                                 o + self._tab.Pos)
        return 0

    # ArrayElement
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None


def ArrayElementStart(builder):
    builder.StartObject(2)


def ArrayElementAddVType(builder, vType):
    builder.PrependUint8Slot(0, vType, 0)


def ArrayElementAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.
                                        UOffsetTFlags.py_type(v), 0)


def ArrayElementEnd(builder):
    return builder.EndObject()
